server:
  port: 18080
security:
  oauth2:
    client:
      clientId: "1000b8470562ed286fe4"
      clientSecret: "882781edf5434e2a5a924045242e2942d1347ca8"
      accessTokenUri: "https://github.com/login/oauth/access_token"
      userAuthorizationUri: "https://github.com/login/oauth/authorize"
      clientAuthenticationScheme: "form"
    resource:
      userInfoUri: "https://api.github.com/user"
spring:
  datasource:
    jdbc-url: jdbc:h2:file:./database.db;Mode=MySQL
    driverClassName: org.h2.Driver